# fly.toml app configuration file generated for wt-deploy-1719558138-client on 2024-06-28T07:02:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wt-deploy-1719558138-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
